# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT

title = "gitleaks config"

[allowlist]
description = "Allowlist for false positives"
files = [
  '''pkg/jwt/parser_test\.go'''
]

[allowlist.rules]
description = "Allow test JWT tokens in parser_test.go"
regexes = [
  '''eyJ[A-Za-z0-9+/=]+'''
]
