swagger: "2.0"
info:
    title: LFX v2 Auth Service
    description: Authentication service providing NATS-based user management with health endpoints
    version: "1.0"
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths: {}
