# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
image:
  repository: ghcr.io/linuxfoundation/lfx-v2-auth-service/server
  # tag is the container image tag (overrides appVersion from Chart.yaml)
  tag: ""
  # pullPolicy is the image pull policy
  pullPolicy: IfNotPresent

# service is the configuration for the Kubernetes service
service:
  # port is the service port
  port: 8080

# app is the configuration for the application
app:
  # use_oidc_contextualizer is a boolean to determine if the OIDC contextualizer should be used
  use_oidc_contextualizer: true
  # environment is the configuration for the application environment
  environment:
    # NATS Configuration
    NATS_URL:
      value: nats://lfx-platform-nats.lfx.svc.cluster.local:4222
    # Repository type for user management
    # It can be authelia, auth0 or mock
    # If not set, it will default to mock
    USER_REPOSITORY_TYPE:
      value: mock
    
    # Auth0 Management API configuration
    ## Optional when using mock or authelia repository type
    AUTH0_TENANT:
      value: null
    AUTH0_DOMAIN:
      value: null
    # Auth0 M2M Authentication configuration
    ## Required when using auth0 repository type
    AUTH0_CLIENT_ID:
      value: null
    AUTH0_PRIVATE_BASE64_KEY:
      value: null
    AUTH0_AUDIENCE:
      value: null
