# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
{{- if eq .Values.app.environment.USER_REPOSITORY_TYPE.value "authelia" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.app.environment.AUTHELIA_CONFIGMAP_NAMESPACE.value }}
  labels:
    app: {{ .Chart.Name }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
# Minimal permissions for Authelia ConfigMap access
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["{{ .Values.app.environment.AUTHELIA_CONFIGMAP_NAME.value }}"]
  verbs: ["get", "update"]
# Minimal permissions for Authelia Secret access  
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["{{ .Values.app.environment.AUTHELIA_SECRET_NAME.value }}"]
  verbs: ["get", "update"]
# Minimal permissions for Authelia DaemonSet restart
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  resourceNames: ["{{ .Values.app.environment.AUTHELIA_DAEMONSET_NAME.value }}"]
  verbs: ["get", "update"]
{{- end }}
